development:
  adapter: postgresql
  database: icarus_database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: icarus_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: icarus_database_production
  pool: 5
  timeout: 5000